# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273fc29597e95ab244b035e0eecabd56cc1cae352d25be8a484d38f508afac75f4e944a54128b0aa773f903aaee8b790fdc5931b02fd2ca75a90e186cba9803d

test:
  secret_key_base: fe815614a2e93eede30c15dec90845120abf82169b8faccd9645bab7889171036f973fc7c8065976fe2d99b689d78540eb46fa4560fc91acea85d4b46a83a1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
